### ISSUE TITLE
Meta 03: Gerenciar o andamento do jogo

### ISSUE THREAD

**Issue by Lakshamana** [Lakshamana/tic-tac-toe#4]
- [ ] Preparo da partida
  - Fica a cargo do *backend* decidir quem jogará com 'X' ou 'O' (via mensagem assíncrona)
   - Enviar mensagem a cada cliente informando qual o símbolo (se é 'X' ou 'O')
- [ ] Permitir que os jogadores da partida selecionem os quadros nos seus respectivos turnos
  - [ ] O *frontend* deve habilitar todos os botões somente quando for a vez do jogador em questão
- [ ] Validar jogadas
  - [ ] Caso uma jogada seja avaliada como válida pelo *backend* a resposta com tipo 'OK' e as posições da jogada (linha e coluna) devem ser enviadas aos clientes da partida
  - [ ] Validação da jogada e verificação de fim de jogo fica a cargo do *backend*
